--- 
- name: Install Nessus server
  hosts: all
  remote_user: student1
  gather_facts: no
  become: yes
  vars:
    nessus_gpg_url: https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/6979/download?i_agree_to_tenable_license_agreement=true
    nessus_download_url: https://www.tenable.com/downloads/api/v1/public/pages/nessus/downloads/11430/download?i_agree_to_tenable_license_agreement=true
  tasks:
    - name: Install nessus gpg key
      rpm_key:
        state: present
        key: "{{ nessus_gpg_url }}"
        
    - name: Download and install nessus
      yum:
        name: "{{ nessus_download_url }}"
        state: present
    
    - name: start the nessus daemon
      service:
        name: nessusd 
        enabled: yes
        state: started

  